language: java
script: ant all
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN 
  keep-history: false
  local-dir: products
  target-branch: master
  repo: winnifredeatonarchive/wea
  on:
    branch: master