language: java
#Have to add ghostscript as an add on for PDF conversion to work properly
addons:
    apt:
        packages:
        - ghostscript
script: ant all
notifications:
  email:
    recepients:
      - joey.takeda@gmail.com #Always email Joey
    on_success: change 
    on_failure: always # Alert when the build fails
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN 
  keep-history: false
  local-dir: products
  target-branch: master
  repo: winnifredeatonarchive/wea
  on:
    branch: master