language: java
before_script:
    "echo $JAVA_OPTS"
    "export JAVA_OPTS=-Xmx1024m"
script: ant all
notifications:
  email:
    recepients:
      - joey.takeda@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN 
  keep-history: false
  local-dir: products
  target-branch: master
  repo: winnifredeatonarchive/wea
  on:
    branch: master