name: Validate accessibility
on:
    workflow_run:
        workflows: [Build]
        types:
            - completed
jobs:
  a11y:
    runs-on: ubuntu-latest
    if:  ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-node@v2
        with:
           node-version: '16'
      - name: Setup NPM    
        run: npm install pa11y-ci pa11y-ci-reporter-html --g