name: Validate accessibility
on:
    workflow_run:
        workflows: [Build]
        types:
            - completed
jobs:
  a11y:
    runs-on: ubuntu-latest
    if:  ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-node@v2
        with:
           node-version: '16'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set environment variables
        run: >
            VERSION=$(cat ${{ github.workspace }}/VERSION);
            SHORT_SHA=`git rev-parse --short HEAD`;
            ARTIFACT_NAME="${VERSION}_${SHORT_SHA}";
            echo "VERSION=${VERSION}" >> $GITHUB_ENV;
            echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV;
            echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV