name: Validate accessibility
on: [push, workflow_dispatch]
concurrency:
    group: ${{ github.ref }}
    # Don't cancel already running builds
    cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
           node-version: '16'
      - name: Wait for Jenkins
        if: ${{ !(env.ACT || github.event_name == 'workflow_dispatch') }}
        run: |
            secs=600 #Ten minutes 
            while [ $secs -gt 0 ]; do
               printf "\rsleep: $((secs%3600/60))m:$((secs%60))s\033[0K" 
               sleep 1 
               : $((secs--)) 
            done
            printf "\n"
      - name: Download pa11y config
        run: >
            curl -s -H "Accept:application/vnd.github.v3.raw"
            https://api.github.com/repos/${{ github.repository }}/contents/.pa11yci
            -o ${{ github.workspace }}/.pa11yci       
      - name: Download node modules
        run: npm install pa11y-ci pa11y-ci-reporter-html --g
      - name: Download package from Jenkins
        run: curl -o ${{github.workspace}}/archive.zip "https://jenkins.hcmc.uvic.ca/job/WEA/lastSuccessfulBuild/artifact/*zip*/archive.zip"
      - name: Unzip
        run: unzip ${{github.workspace}}/archive.zip -d ${{ github.workspace }}
      - name: Run accessibility checks
        run: pa11y-ci ${{ github.workspace}}/archive/products/site/*.html
      - name: Archive diagnostic reports
        uses: actions/upload-artifact@v2
        with:
            name: pa11y-ci-report
            path: pa11y-ci-report
        