name: Validate accessibility
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Jenkins
        if: ${{ !(env.ACT || github.event_name == 'workflow_dispatch') }}
        run: |
            secs=5 
            while [ $secs -gt 0 ]; do
               printf "\rsleep: $((secs%3600/60))m:$((secs%60))s\033[0K" 
               sleep 1 
               : $((secs--)) 
            done
            printf "\n"
      - name: Download repo assets
        run: ls -l
      - name: Validate
        run: echo "Validate stuff"
